version: '3'

secrets:
  vncpasswd:
    file: ./vncpasswd.txt

services:
 jumpbox:
  image: ghcr.io/parttimer777/docker-jumpbox:latest
  container_name: jumpbox
  hostname: jumpbox   # system's hostname
  environment:
    - PUID=1001
    - PGID=1001
    - TZ=America/New_York
    - VNC_USERNAME=${VNC_USERNAME:?err}
    - SYSLOG_TARGET_SERVER=${SYSLOG_TARGET_SERVER:?err}
    - SYSLOG_TARGET_PORT=${SYSLOG_TARGET_PORT:?err}
  restart: unless-stopped
  secrets:
    - vncpasswd
