version: '3'

secrets:
  vncpasswd:
    file: ./vncpasswd.txt

services:
 jumpbox:
  image: ghcr.io/parttimer777/docker-jumpbox:latest
  container_name: jumpbox
  hostname: jumpbox   # system's hostname
  environment:
    - PUID=1001
    - PGID=1001
    - TZ=America/New_York
  restart: unless-stopped
  secrets:
    - vncpasswd
