#!/usr/bin/with-contenv bash

echo "***** starting vnc as $VNC_USERNAME *****"
# accept connection only from localhost (noVNC service) 
# disable password requirement (SecurityTypes)
exec runuser -u $VNC_USERNAME -- vncserver \
    -localhost yes \
    -depth 16 -fg :0  \
    -SecurityTypes None 
