#!/usr/bin/with-contenv bash

echo "***** starting rsyslogd *****"


output=""
if [ -n "$SYSLOG_TARGET_HOST" ]; then
    echo "configuring syslog target $SYSLOG_TARGET_HOST:$SYSLOG_TARGET_PORT"
    output="$(cat <<EOF
*.* action(type="omfwd" protocol="tcp" target="$SYSLOG_TARGET_HOST" port="$SYSLOG_TARGET_PORT" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted" KeepAlive="on" action.resumeRetryCount="60" queue.type="linkedlist" queue.size="50000")
EOF
)"
fi
echo "$output" > /etc/rsyslog.d/99-remote-target.conf

exec rsyslogd -f /etc/rsyslog.conf -n