name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3

      # Now check if our parent image changed. The result will be available at `steps.[id of this step].outputs.out-of-date`
    - name: Check if we have to even do all this
      id: check
      uses: twiddler/is-my-docker-parent-image-out-of-date@v1
      with:
        parent-image: ghcr.io/linuxserver/baseimage-debian:bookworm
        my-image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
       

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: steps.check.outputs.out-of-date == 'true'

        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      if: steps.check.outputs.out-of-date == 'true'

       
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
